DROP TABLE IF EXISTS financial_operations CASCADE;
DROP TABLE IF EXISTS financial_categories CASCADE;

DROP TABLE IF EXISTS cargo_items CASCADE;
DROP TABLE IF EXISTS cargo_shipments CASCADE;
DROP TABLE IF EXISTS cargo_statements CASCADE;
DROP TABLE IF EXISTS flights CASCADE;
DROP TABLE IF EXISTS flight_types CASCADE;
DROP TABLE IF EXISTS cargo_types CASCADE;

DROP TABLE IF EXISTS excursion_bookings CASCADE;
DROP TABLE IF EXISTS excursion_schedule CASCADE;
DROP TABLE IF EXISTS excursions CASCADE;
DROP TABLE IF EXISTS excursion_agencies CASCADE;

DROP TABLE IF EXISTS accommodations CASCADE;
DROP TABLE IF EXISTS hotel_rooms CASCADE;
DROP TABLE IF EXISTS child_companions CASCADE;
DROP TABLE IF EXISTS visas CASCADE;
DROP TABLE IF EXISTS group_members CASCADE;
DROP TABLE IF EXISTS hotels CASCADE;
DROP TABLE IF EXISTS tourist_groups CASCADE;
DROP TABLE IF EXISTS identity_documents CASCADE;
DROP TABLE IF EXISTS tourists CASCADE;
DROP TABLE IF EXISTS tourist_categories CASCADE;

DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;

DROP DOMAIN IF EXISTS non_empty_varchar_255;
